version: "3.0"
services:
  app:
    container_name: extendedExamAnalysis

    build: ./app
    ports:
      - 8180:8180

    user: 'root'
    volumes:
      - ./app:/app
    networks:
      - pysubnet

networks:
  pysubnet:
    name: ilias_dev_subnet
